// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// discWindowArea
Rcpp::NumericVector discWindowArea(Rcpp::NumericVector x, Rcpp::NumericVector y, double r, int npoly, Rcpp::List rings);
RcppExport SEXP _lisaClust_discWindowArea(SEXP xSEXP, SEXP ySEXP, SEXP rSEXP, SEXP npolySEXP, SEXP ringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type npoly(npolySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rings(ringsSEXP);
    rcpp_result_gen = Rcpp::wrap(discWindowArea(x, y, r, npoly, rings));
    return rcpp_result_gen;
END_RCPP
}
// localCurvesR
Rcpp::List localCurvesR(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, int nTypes, Rcpp::NumericVector Rs, Rcpp::NumericVector labelVal, Rcpp::NumericVector wt, Rcpp::NumericVector lam, Rcpp::NumericMatrix edge, bool Lfunction);
RcppExport SEXP _lisaClust_localCurvesR(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP nTypesSEXP, SEXP RsSEXP, SEXP labelValSEXP, SEXP wtSEXP, SEXP lamSEXP, SEXP edgeSEXP, SEXP LfunctionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type labelVal(labelValSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< bool >::type Lfunction(LfunctionSEXP);
    rcpp_result_gen = Rcpp::wrap(localCurvesR(x, y, type, nTypes, Rs, labelVal, wt, lam, edge, Lfunction));
    return rcpp_result_gen;
END_RCPP
}
// nearestLabelsR
Rcpp::IntegerVector nearestLabelsR(Rcpp::NumericVector tx, Rcpp::NumericVector ty, Rcpp::IntegerVector label, Rcpp::NumericVector qx, Rcpp::NumericVector qy);
RcppExport SEXP _lisaClust_nearestLabelsR(SEXP txSEXP, SEXP tySEXP, SEXP labelSEXP, SEXP qxSEXP, SEXP qySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type label(labelSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type qx(qxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type qy(qySEXP);
    rcpp_result_gen = Rcpp::wrap(nearestLabelsR(tx, ty, label, qx, qy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lisaClust_discWindowArea", (DL_FUNC) &_lisaClust_discWindowArea, 5},
    {"_lisaClust_localCurvesR", (DL_FUNC) &_lisaClust_localCurvesR, 10},
    {"_lisaClust_nearestLabelsR", (DL_FUNC) &_lisaClust_nearestLabelsR, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_lisaClust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
