# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.discWindowArea <- function(x, y, r, npoly, rings) {
    .Call(`_lisaClust_discWindowArea`, x, y, r, npoly, rings)
}

.localCurves <- function(x, y, type, nTypes, Rs, labelVal, wt, lam, edge, Lfunction, includeSelf = TRUE) {
    .Call(`_lisaClust_localCurvesR`, x, y, type, nTypes, Rs, labelVal, wt, lam, edge, Lfunction, includeSelf)
}

.nearestLabels <- function(tx, ty, label, qx, qy) {
    .Call(`_lisaClust_nearestLabelsR`, tx, ty, label, qx, qy)
}

.concaveHull <- function(x, y, concavity, lengthThreshold) {
    .Call(`_lisaClust_concaveHullR`, x, y, concavity, lengthThreshold)
}

